# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider :virtualbox do |vbox|
        vbox.customize ["modifyvm", :id, "--memory", "4096"]
        vbox.customize ["modifyvm", :id, "--cableconnected1", "on"]
      end
end
